"use client";

import { CheckCircle, ShieldWarning } from "@/components/huge-icons";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { WhatsAppConnectDialog } from "@/components/whatsapp/whatsapp-connect-dialog";
import { getWhatsAppConnection } from "./whatsapp-actions";

type Connection = Awaited<ReturnType<typeof getWhatsAppConnection>>;

export function WhatsAppPage({ initial, returnTo }: { initial: Connection; returnTo?: string }) {
  const ready = initial.status === "ready";
  return <main className="flex min-h-full flex-col gap-6 bg-background p-4 lg:p-6"><div><p className="text-xs font-medium text-primary">INTEGRAÇÕES</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Integração WhatsApp</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Conecte o WhatsApp operacional da corretora. O sistema só importa mensagens ligadas a leads.</p></div><Card className="border-warning/30 bg-accent/10 shadow-none"><CardContent className="flex items-start gap-3 p-5"><ShieldWarning className="mt-0.5 size-6 shrink-0 text-warning" /><div><p className="font-semibold text-warning-foreground">Privacidade por lead</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Conversas pessoais, grupos e números sem vínculo são descartados antes de qualquer gravação.</p></div></CardContent></Card><Card className="border-border bg-card shadow-none"><CardHeader><CardTitle>Conexão operacional</CardTitle><CardDescription>Abra o componente para gerar ou ler o QR Code e controlar o chat.</CardDescription></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold">{ready ? "WhatsApp conectado" : "WhatsApp ainda não conectado"}</p><p className="mt-1 text-xs text-muted-foreground">{ready ? "O chat interno está pronto para os atendimentos." : "A conexão pode ser aberta deste card ou por qualquer botão do sistema."}</p></div><WhatsAppConnectDialog initial={initial} returnTo={returnTo} /></CardContent></Card><Card className="border-border bg-card shadow-none"><CardHeader><CardTitle className="flex items-center gap-2"><CheckCircle className="text-primary" /> Como o atendimento funciona</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm text-muted-foreground md:grid-cols-3"><p><strong className="text-foreground">1. Conecte:</strong> abra o dialog e leia o QR Code.</p><p><strong className="text-foreground">2. Atenda:</strong> o corretor envia mensagens na tela do lead.</p><p><strong className="text-foreground">3. Proteja:</strong> apenas mensagens vinculadas a leads são importadas.</p></CardContent></Card></main>;
}
