import type { TenantRole } from "@/shared/db/schema";

export const PERMISSIONS = {
  acessar_conversas: ["broker", "manager", "director"],
  acessar_leads: ["broker", "manager", "director"],
  acessar_tarefas: ["broker", "manager", "director"],
  acessar_cotacoes: ["broker", "manager", "director"],
  acessar_documentos: ["broker", "manager", "director"],
  acessar_clientes: ["broker", "manager", "director"],
  acessar_vendas: ["broker", "manager", "director"],
  acessar_dashboard: ["broker", "manager", "director"],
  acessar_relatorios: ["manager", "director"],
  acessar_catalogo: ["director"],
  acessar_configuracoes: ["broker", "manager", "director"],
  acessar_configuracoes_pessoais: ["broker", "manager", "director"],
  configurar_whatsapp_proprio: ["broker", "manager", "director"],
  acessar_configuracoes_unidade: ["manager", "director"],
  gerenciar_configuracoes_unidade: ["manager", "director"],
  acessar_roadmap: ["director"],
  acessar_guia: ["broker", "manager", "director"],
  acessar_notificacoes: ["broker", "manager", "director"],
  acessar_financeiro: ["broker", "manager", "director"],
  ver_fluxo_caixa: ["manager", "director"],
  ver_resultado_corretor: ["manager", "director"],
  ver_comissionamento: ["director"],
  ver_taxas_custos: ["manager", "director"],
  ver_relatorios_financeiros: ["manager", "director"],
  ver_cronograma_repasses: ["manager", "director"],
  gerenciar_financeiro: ["director"],
  criar_lead_manual: ["broker", "manager", "director"],
  ver_dashboard_equipe: ["manager", "director"],
  ver_dashboard_pessoal: ["broker"],
  convidar_gestor: ["director"],
  convidar_corretor: ["director", "manager"],
  gerenciar_filiais: ["director"],
  ver_painel_integridade: ["manager", "director"],
  ver_comissao_propria: ["broker", "manager", "director"],
  ver_comissao_equipe: ["manager", "director"],
  gerenciar_comissoes: ["director"],
  gerenciar_metas: ["director", "manager"],
  ver_meta_propria: ["broker"],
  ver_meta_equipe: ["manager", "director"],
  exportar_relatorios: ["manager", "director"],
  aprovar_documentos: ["manager", "director"],
  configurar_white_label: ["director"],
  alterar_status_lead: ["broker", "manager", "director"],
  reabrir_lead_perdido: ["manager", "director"],
  leads_view_all: ["director"],
  leads_route_to_unit: ["director", "manager"],
  leads_assign: ["director", "manager"],
  leads_reassign: ["director", "manager"],
  leads_bulk_assign: ["director", "manager"],
  lead_queues_view: ["director", "manager"],
  lead_queues_manage: ["director", "manager"],
  distribution_settings_manage: ["director", "manager"],
  duty_schedules_manage: ["director", "manager"],
  distribution_audit_view: ["director", "manager"],
} as const satisfies Record<string, readonly TenantRole[]>;

export type PermissionKey = keyof typeof PERMISSIONS;

export function hasPermission(role: TenantRole | string | null | undefined, permission: PermissionKey) {
  return role != null && (PERMISSIONS[permission] as readonly string[]).includes(role);
}
