"use client";

import { useState } from "react";
import { toast } from "sonner";
import { FileArrowDown, FileText } from "@/components/huge-icons";
import { Button } from "@/components/ui/button";
import { Dialog, DialogClose, DialogDescription, DialogPopup, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { importLeadsFromCsvAction } from "@/features/leads/bulk-import";

type Branch = { id: string; name: string };
export function BulkLeadImportDialog({ branches, role, jobTitle, branchId }: { branches: Branch[]; role: "director" | "manager" | "broker"; jobTitle: string; branchId: string | null }) {
  const isCentralMarketing = jobTitle === "marketing" && branchId === null;
  const canChooseBranch = role === "director" || isCentralMarketing;
  const canImport = role === "director" || role === "manager" || isCentralMarketing;
  const [open, setOpen] = useState(false); const [selectedBranch, setSelectedBranch] = useState(branchId ?? ""); const [file, setFile] = useState<File | null>(null); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); const [result, setResult] = useState<{ imported: number; duplicates: number; errors: Array<{ row: number; message: string }> } | null>(null);
  function downloadTemplate() { const blob = new Blob(["nome,telefone,email\nMaria da Silva,5521999999999,maria@exemplo.com\n"], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "modelo-leads-corretop.csv"; anchor.click(); URL.revokeObjectURL(url); }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!file) return toast.error("Selecione um arquivo CSV."); if (!consent) return toast.error("Confirme que possui base legal para importar os contatos."); setBusy(true); setResult(null); const data = new FormData(); data.set("file", file); data.set("branchId", selectedBranch); data.set("consentimento", "true"); const response = await importLeadsFromCsvAction(data); setBusy(false); if (!response.success) return toast.error(response.error); const imported = response.imported ?? 0; const duplicates = response.duplicates ?? 0; const errors = response.errors ?? []; setResult({ imported, duplicates, errors }); toast.success(`${imported} lead(s) importado(s).`); }
  if (!canImport) return null;
  return <><Button onClick={() => setOpen(true)} variant="outline"><FileText /> Importar leads</Button><Dialog open={open} onOpenChange={setOpen}><DialogPopup className="max-h-[85vh] overflow-y-auto sm:max-w-xl"><DialogTitle>Importar leads em massa</DialogTitle><DialogDescription>Envie um CSV com as colunas nome, telefone e e-mail. Os leads entram no fluxo normal da unidade.</DialogDescription><form onSubmit={submit} className="grid gap-4"><Button type="button" variant="ghost" className="justify-start" onClick={downloadTemplate}><FileArrowDown /> Baixar modelo CSV</Button>{canChooseBranch ? <div className="grid gap-2"><label className="text-sm font-medium">Unidade de destino</label><Select value={selectedBranch} onValueChange={(value) => setSelectedBranch(value ?? "")}><SelectTrigger><SelectValue placeholder="Selecione uma unidade" /></SelectTrigger><SelectContent>{branches.map((branch) => <SelectItem key={branch.id} value={branch.id}>{branch.name}</SelectItem>)}</SelectContent></Select></div> : <p className="rounded-md bg-muted/50 px-3 py-2 text-xs text-muted-foreground">Os leads serão importados para sua unidade.</p>}<Input type="file" accept=".csv,text/csv" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><p className="text-xs text-muted-foreground">Máximo de 500 leads e 2 MB por arquivo. Telefones devem estar em formato brasileiro com DDD.</p><label className="flex items-start gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-0.5 size-4 rounded border-border" />Confirmo que possuo base legal ou consentimento para importar e tratar os dados destes contatos.</label>{result ? <div className="grid gap-1 rounded-lg border border-border bg-muted/30 p-3 text-sm"><p><strong>{result.imported}</strong> importados · <strong>{result.duplicates}</strong> duplicados ignorados</p>{result.errors.length ? <p className="text-destructive">{result.errors.length} linha(s) com erro: {result.errors.slice(0, 3).map((item) => `linha ${item.row} (${item.message})`).join(", ")}{result.errors.length > 3 ? "…" : ""}</p> : <p className="text-success">Arquivo processado sem erros.</p>}</div> : null}<div className="flex justify-end gap-2"><DialogClose render={<Button type="button" variant="ghost">Cancelar</Button>} /><Button type="submit" disabled={busy || !file || !consent || (canChooseBranch && !selectedBranch)}>{busy ? "Importando…" : "Importar leads"}</Button></div></form></DialogPopup></Dialog></>;
}
